data_dir: "data"
output_dir: "output"
models_dir: "output/models"

problem:
  name: "adder"  # "adder", "multiplier", "parity", "sorter"
  bits: 2        # Number of bits for each input number
  num_samples: 1000000000  # Number of samples to generate, will cap out at the max for that number of bits

model:
  hidden_dims: [16, 16, 8]
  device: "cuda"  # "cpu" or "cuda"
  grad_factor: 1.0

training:
  num_epochs: 20
  batch_size: 4
  learning_rate: 0.001
  weight_decay: 0.0001
  train_ratio: 0.8
